import Head from 'next/head'

import Main from './../components/Main';

export default function Home({ data }) {
	if (data.length < 1) return <div>Lodding ...</div>;

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main data={data} />
		</div>
	);
}
export async function getServerSideProps() {
	const API = process.env.API;


	const res = await fetch(
		`https://api.openweathermap.org/data/2.5/weather?q=Rawson&units=metric&appid=${API}`,
	);
	const data = await res.json();

	if (!data) {
		return {
			notFound: true,
		};
	}

	return {
		props: { data }, // will be passed to the page component as props
	};
}